In [2]:
import pandas as pd
import numpy as np
import cvxpy as cvx
import helper
import project_helper
import os
import pandas_datareader.data as pdr
import datetime as dt
import requests_cache
from alpha_vantage.timeseries import TimeSeries
# quandl key
f = open("/Users/manwaiwong/key/quandl.txt","r")

if f.mode == 'r':
    c = f.read() 

In [2]:
# quandl 
tickers = ["HKEX/00388","HKEX/01810","HKEX/02342", "HKEX/00552"]
expire_after = dt.timedelta(days=1)
session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)
start = dt.date.today() - dt.timedelta(1095)
end = dt.date.today() 
qkey = c


close = pd.DataFrame() # dataframe to store close price of each ticker
volumes = pd.DataFrame()
dividends = pd.DataFrame()
attempt = 0 # initializing passthrough variable
drop = [] # initializing list to store tickers whose close price was successfully extracted
## loop tickers get data
while len(tickers) != 0 and attempt <= 5:
    tickers = [j for j in tickers if j not in drop] # removing stocks whose data has been extracted from the ticker list
    for i in range(len(tickers)):
        try:
            temp = pdr.DataReader(tickers[i], 'quandl', start, end, api_key=qkey, session=session)
            #print(start)
            #print(end)
            #print(temp)
            close[tickers[i]] = temp["PreviousClose"]
            volumes[tickers[i]] = temp["ShareVolume000"]
            dividends[tickers[i]] = temp["PEx"].fillna(0)
            #temp.dropna(inplace = True)
            drop.append(tickers[i])       
        except:
            print(tickers[i]," :failed to fetch data...retrying")
            continue
    attempt+=1




In [3]:
close

HKEX/00388  HKEX/01810  HKEX/02342  HKEX/00552
Date                                                      
2020-02-14       268.8       13.38        3.11        5.84
2020-02-13       270.4       12.92        3.11        5.93
2020-02-12       270.2       12.78        3.12        5.80
2020-02-11       268.4       12.96        3.16        5.82
2020-02-10       270.6       12.84        3.19        5.71
...                ...         ...         ...         ...
2017-02-21       200.8         NaN        1.50        5.02
2017-02-20       200.2         NaN        1.45        5.04
2017-02-17       202.4         NaN        1.49        5.19
2017-02-16       202.0         NaN        1.51        5.14
2017-02-15       197.8         NaN        1.52        5.08

[737 rows x 4 columns]

# numpy basic

In [4]:
# 
w = np.zeros((2,5),dtype=int)
w

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
# fill any value
c = np.ones((2,6))
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [7]:
y = np.full((5,2), 9)
y

array([[9, 9],
       [9, 9],
       [9, 9],
       [9, 9],
       [9, 9]])

In [9]:
e = np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
o = np.diag([10,20,30,40,50])
o

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

In [13]:
# highly use
t = np.arange(10)
t

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
t = np.arange(4,10)
t

array([4, 5, 6, 7, 8, 9])

In [15]:
t = np.arange(1,14,5)
t

array([ 1,  6, 11])

In [19]:
t = np.linspace(0,10,10)
t

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [28]:
t = np.linspace(0,30,30, endpoint = False) #  dtype = int is optional
t

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [29]:
# reshape : array to matrix, 
# array 't' must compaticable with array length you definded
# t legth is 10
t = np.reshape(t, (6,5))
t

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.]])

In [31]:
t = np.reshape(t, (3,10))
t

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.]])

In [33]:
y = np.linspace(0,50,10, endpoint=False).reshape(5,2)
y

array([[ 0.,  5.],
       [10., 15.],
       [20., 25.],
       [30., 35.],
       [40., 45.]])

In [35]:
# randam numpy array
g = np.random.random((3,3))
g

array([[0.53814138, 0.32004926, 0.35515907],
       [0.9561919 , 0.5588261 , 0.16146489],
       [0.11385291, 0.03146493, 0.58584359]])

In [37]:
g = np.random.randint(4,15,(3,2))
g

array([[ 8,  6],
       [14,  4],
       [ 7,  4]])

In [42]:
#np.random.normal(mean, standard deviation)
g = np.random.normal(0,0.1,size=(1000,1000))
g

array([[-0.08587577,  0.04347438,  0.04035904, ..., -0.07935574,
        -0.074868  ,  0.11253852],
       [-0.09026651, -0.11755544, -0.17959371, ..., -0.04206396,
         0.00510575,  0.10189643],
       [ 0.06414886,  0.07241306,  0.30012584, ...,  0.18375804,
         0.04256235,  0.16196301],
       ...,
       [ 0.01337882, -0.00042557,  0.00547885, ..., -0.12881813,
         0.1134266 , -0.06683027],
       [-0.09608122,  0.0457032 ,  0.12106317, ...,  0.07872921,
         0.0663866 ,  0.08816424],
       [-0.14095576,  0.00206297, -0.03369086, ...,  0.12570095,
         0.37690882, -0.04207765]])

In [45]:
print('mean ={}'.format(g.mean()) )
print('mean', g.std())
print('mean', g.max())
print('mean', g.min())
print('# positive', (g > 0 ).sum())
print('# negative', (g < 0 ).sum())

mean =-0.0001626137525673897
mean 0.09996236075543506
mean 0.5134686189087474
mean -0.5047099346427711
# positive 499343
# negative 500657


In [51]:
X = np.arange(2,34,2).reshape(4,4)
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

# Accessing and deleting

In [52]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [55]:
print('1st element is  {}'.format(x[0]))
print('1st element is  {}'.format(x[-1]))

1st element is  1
1st element is  5


In [57]:
x[3] = 999
x

array([  1,   2,   3, 999,   5])

In [59]:
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
x[0,0] = 999
x

array([[999,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [64]:
x[2,1] = 19
x

array([[999,   2,   3],
       [  4,   5,   6],
       [  7,  19,   9]])

In [72]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.delete(x,[0,5])
x
#
u = np.array([1,2,3,4,5,6,7,8,9,10])
u = np.delete(u,[1,9])
u

array([1, 3, 4, 5, 6, 7, 8, 9])

In [75]:
y = np.arange(1,10).reshape(3,3)
print(y)
w = np.delete(y,0,axis = 0)
print('\n',w)
v = np.delete(y,[0,2], axis = 1)
print('\n', v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [76]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.append(x,[88,99,999])
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  88,  99, 999])

In [78]:
o = np.arange(1,10).reshape(3,3)
o

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
u = np.append(o,[[10,11,12]],axis=0)
u

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
v = np.append(o,[[10],[11],[12]],axis=1)
v

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9,10])


# Slicing
1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [98]:
x = np.arange(1,21).reshape(4,5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [86]:
z =x[1:4,2:5]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [87]:
z =x[1:,2:]
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [88]:
r =x[:3,:2]
r

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [89]:
u = x[:,2]
u

array([ 3,  8, 13, 18])

In [90]:
u = x[:,2:3]
u

array([[ 3],
       [ 8],
       [13],
       [18]])

In [97]:
x

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19, 999]])

In [101]:
z[2,2] = 999
z

array([[  8,   9,  10],
       [ 13,  14,  15],
       [ 18,  19, 999]])

In [102]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [103]:
z = x[1:,2:].copy()
z

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [104]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [105]:
np.unique(x)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Boolean Indexing, Set Operations, and Sorting


In [107]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Boolean 

In [109]:
print(x[x>20])

[21 22 23 24]


In [110]:
print(x[x<4])

[0 1 2 3]


In [113]:
print(x[( x > 10) & (x < 17) ])

[11 12 13 14 15 16]


In [115]:
x[( x > 10) & (x < 17) ] = -1
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, -1, -1, -1, -1],
       [-1, -1, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [121]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,9,4])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 9]


In [125]:
# sort change original data
x = np.random.randint(1,11, size = (10,))
print(x)

[ 2  8  8 10  2  8  7  4  7  3]


In [128]:
print(np.sort(x))
x

[ 2  2  3  4  7  7  8  8  8 10]


array([ 2,  8,  8, 10,  2,  8,  7,  4,  7,  3])

In [130]:
#change originial
x.sort()
x

array([ 2,  2,  3,  4,  7,  7,  8,  8,  8, 10])

In [131]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 5  8  1  2  4]
 [10  4  3  2  1]
 [ 8  8  3  7  4]
 [10  3  8  5  6]
 [ 7  6  8  1  1]]


X with sorted columns :
 [[ 5  3  1  1  1]
 [ 7  4  3  2  1]
 [ 8  6  3  2  4]
 [10  8  8  5  4]
 [10  8  8  7  6]]

X with sorted rows :
 [[ 1  2  4  5  8]
 [ 1  2  3  4 10]
 [ 3  4  7  8  8]
 [ 3  5  6  8 10]
 [ 1  1  6  7  8]]


# Arithmetic operations and Broadcasting


In [139]:
x = np.array([1,2,3,4,5])
y = np.array([6.1,7.1,8.2,9.6,10.1])

In [140]:
x+y

array([ 7.1,  9.1, 11.2, 13.6, 15.1])

In [141]:
# We perfrom basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x + y =  [ 7.1  9.1 11.2 13.6 15.1]
add(x,y) =  [ 7.1  9.1 11.2 13.6 15.1]

x - y =  [-5.1 -5.1 -5.2 -5.6 -5.1]
subtract(x,y) =  [-5.1 -5.1 -5.2 -5.6 -5.1]

x * y =  [ 6.1 14.2 24.6 38.4 50.5]
multiply(x,y) =  [ 6.1 14.2 24.6 38.4 50.5]

x / y =  [0.16393443 0.28169014 0.36585366 0.41666667 0.4950495 ]
divide(x,y) =  [0.16393443 0.28169014 0.36585366 0.41666667 0.4950495 ]


In [142]:
print(x)
print(y)

[1 2 3 4 5]
[ 6.1  7.1  8.2  9.6 10.1]


In [145]:
x = np.array([1,2,3,4,5,6]).reshape(2,3)
y = np.array([6.1,7.1,8.2,9.6,10.1,11.5]).reshape(2,3)

In [146]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [147]:
y

array([[ 6.1,  7.1,  8.2],
       [ 9.6, 10.1, 11.5]])

In [149]:
# We perform basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))

x + y =  [[ 7.1  9.1 11.2]
 [13.6 15.1 17.5]]
add(x,y) =  [[ 7.1  9.1 11.2]
 [13.6 15.1 17.5]]

x - y =  [[-5.1 -5.1 -5.2]
 [-5.6 -5.1 -5.5]]
subtract(x,y) =  [[-5.1 -5.1 -5.2]
 [-5.6 -5.1 -5.5]]

x * y =  [[ 6.1 14.2 24.6]
 [38.4 50.5 69. ]]
multiply(x,y) =  [[ 6.1 14.2 24.6]
 [38.4 50.5 69. ]]

x / y =  [[0.16393443 0.28169014 0.36585366]
 [0.41666667 0.4950495  0.52173913]]
divide(x,y) =  [[0.16393443 0.28169014 0.36585366]
 [0.41666667 0.4950495  0.52173913]]


In [150]:
x = np.array([1,2,3,4])

# We print x
print()
print('x = ', x)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =', np.exp(x))
print()
print('SQRT(x) =',np.sqrt(x))
print()
print('POW(x,2) =',np.power(x,2)) # We raise all elements to the power of 2


x =  [1 2 3 4]

EXP(x) = [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) = [1.         1.41421356 1.73205081 2.        ]

POW(x,2) = [ 1  4  9 16]


In [151]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


In [152]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


In [153]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [171]:
iu = np.arange(0,100,4).reshape(5,5)
iu

array([[ 0,  4,  8, 12, 16],
       [20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56],
       [60, 64, 68, 72, 76],
       [80, 84, 88, 92, 96]])

In [173]:
r = np.ones((4,4))*np.arange(1,5)
r

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])